### ISSUE TITLE
Error: selectedPrice is not assignable

### ISSUE THREAD

**Issue by FoxMiner** [jestersimpps/cryptotrader#10]
I'm having trouble starting the client.
throws this error

-------------------------------

** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
 10% building modules 3/3 modules 0 active[HPM] Proxy created: /api  ->  https://api.chucknorris.io
[HPM] Proxy rewrite rule created: "^/api" ~> ""
Date: 2017-10-05T18:32:08.940Z
Hash: 794072d1fa094623368f
Time: 10984ms
chunk {inline} inline.bundle.js, inline.bundle.js.map (inline) 5.83 kB [entry] [rendered]
chunk {main} main.bundle.js, main.bundle.js.map (main) 1.06 kB {vendor} [initial] [rendered]
chunk {polyfills} polyfills.bundle.js, polyfills.bundle.js.map (polyfills) 323 bytes {inline} [initial] [rendered]
chunk {styles} styles.bundle.js, styles.bundle.js.map (styles) 238 kB {inline} [initial] [rendered]
chunk {vendor} vendor.bundle.js, vendor.bundle.js.map (vendor) 338 kB [initial] [rendered]

ERROR in C:/xampp/htdocs/cryptotrader/client/src/app/poloniex/poloniex.component.ts (34,41): Type '{ name: string; selectedPrice: any; }[]' is not assignable to
 type 'CurrencyPair[]'.
  Type '{ name: string; selectedPrice: any; }' is not assignable to type 'CurrencyPair'.
    Property 'timestamp' is missing in type '{ name: string; selectedPrice: any; }'.

webpack: Failed to compile.

**Comment by jestersimpps** [comment]
Hi, I recently made a switch to a nodejs backend. You can now run both back and frontend using npm start. Open a third terminal to load in ticker data in redis: npm run loaddata
